FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
# "COPY . ." signifie : Copier TOUT le contenu local (.) 
# vers le WORKDIR de l'image (.) avec un espace entre les deux.
ARG BUILD_ID=local
ENV VITE_BUILD_ID=$BUILD_ID
COPY . .
RUN npm run build
FROM nginx:alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]